trigger: none

pool:
  vmImage: 'ubuntu-18.04'

variables:
- group: JMETER_TERRAFORM_SETTINGS
- name: JMETER_DIRECTORY_INPUT
  value: $(System.DefaultWorkingDirectory)/jmeter
- name: JMETER_DIRECTORY_OUTPUT
  value: $(System.DefaultWorkingDirectory)/results
- name: TERRAFORM_VERSION
  value: 0.13.2

steps:

- task: AzureCLI@2
  displayName: 'SETUP: Validate JMeter Docker Image'
  inputs:
    azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr login -n $(TF_VAR_JMETER_ACR_NAME)
      docker pull $(TF_VAR_JMETER_DOCKER_IMAGE)

- script: |
    docker run --name=jmx-validator -v $(JMETER_DIRECTORY_INPUT):/jmeter -w /jmeter \
      --entrypoint "TestPlanCheck.sh" $(TF_VAR_JMETER_DOCKER_IMAGE) \
      --stats --tree-dump --jmx $(TF_VAR_JMETER_JMX_FILE)
  displayName: 'SETUP: Validate JMX File'
 
- script: |
    sudo sed 's/API_KEY/'$(API_KEY)'/g; s/SEARCH_SERVICE_NAME/'$(SEARCH_SERVICE_NAME)'/g; s/SEARCH_INDEX_NAME/'$(SEARCH_INDEX_NAME)'/g' $(JMETER_DIRECTORY_INPUT)/$(TF_VAR_JMETER_JMX_FILE) > $(JMETER_DIRECTORY_INPUT)/tmp.jmx
    mv $(JMETER_DIRECTORY_INPUT)/tmp.jmx $(JMETER_DIRECTORY_INPUT)/$(TF_VAR_JMETER_JMX_FILE)
  displayName: 'SETUP: Populate API key, service name, and index name for search in jmx config jmeter file'
 
- task: AzureCLI@2
  displayName: 'SETUP: Prepare Terraform Credentials'
  inputs:
    azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
    scriptType: bash
    scriptLocation: inlineScript
    addSpnToEnvironment: true
    inlineScript: |
      echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
      echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$servicePrincipalKey"
      echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
      echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$AZURE_SUBSCRIPTION_ID"

- script: |
    wget https://releases.hashicorp.com/terraform/$(TERRAFORM_VERSION)/terraform_$(TERRAFORM_VERSION)_linux_amd64.zip
    unzip terraform_$(TERRAFORM_VERSION)_linux_amd64.zip
    sudo mv ./terraform  /usr/local/bin
  workingDirectory: $(Agent.TempDirectory)
  displayName: 'SETUP: Install Terraform'

- script: terraform init
  workingDirectory: ./terraform
  displayName: 'SETUP: Run Terraform Init'

- script: terraform apply -target azurerm_storage_share.jmeter_share -auto-approve
  workingDirectory: ./terraform
  displayName: 'SETUP: Run Terraform Apply (target=file share)'

- task: AzureCLI@2
  displayName: 'SETUP: Transfer JMeter Files to Storage Account'
  inputs:
    azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
    scriptType: 'bash'
    workingDirectory: ./terraform
    scriptLocation: 'inlineScript'
    inlineScript: |
      SHARENAME=$(terraform output storage_file_share_name)
      ACCOUNTNAME=$(terraform output storage_account_name)
      STGKEY=$(terraform output storage_account_key)
      az storage file upload-batch --account-key $STGKEY --account-name $ACCOUNTNAME --destination $SHARENAME --source $(JMETER_DIRECTORY_INPUT)

- script: terraform apply -auto-approve
  workingDirectory: ./terraform
  displayName: 'SETUP: Run Terraform Apply (target=all)'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
    workingDirectory: ./terraform
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      RG=$(terraform output resource_group_name)
      NAME=$(terraform output jmeter_controller_name)
      echo "`date`: Started!"
      sleep 10
      while [ $(az container show -g $RG -n $NAME --query "containers[0].instanceView.currentState.state" -o tsv) == "Running" ]; do
        echo "`date`: Still Running..."
        sleep 20
      done
      echo "`date`: Finished!"
  displayName: 'TEST: Wait Test Execution'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
    workingDirectory: ./terraform
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az container logs -g $(terraform output resource_group_name) -n $(terraform output jmeter_controller_name)
      RESOURCE_GROUP=$(terraform output resource_group_name)
      echo -n $(terraform output jmeter_workers_names) | xargs -t -d "," -I '{}' -n1 az container logs -g $RESOURCE_GROUP -n {}
  displayName: 'RESULTS: Collect JMeter Controller and Worker Logs'

- task: AzureCLI@2
  displayName: 'RESULTS: Download Jmeter results'
  inputs:
    azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
    scriptType: 'bash'
    workingDirectory: ./terraform
    scriptLocation: 'inlineScript'
    inlineScript: |
      RG=$(terraform output resource_group_name)
      SHARENAME=$(terraform output storage_file_share_name)
      STGKEY=$(terraform output storage_account_key)
      ACCOUNTNAME=$(terraform output storage_account_name)
      mkdir $(System.DefaultWorkingDirectory)/results
      az storage file download-batch --account-key $STGKEY --account-name $ACCOUNTNAME --destination $(JMETER_DIRECTORY_OUTPUT) --no-progress --source $SHARENAME

- script: |
    JMETER_RESULTS=$(JMETER_DIRECTORY_OUTPUT)/$(terraform output jmeter_results_file)
    JUNIT_RESULTS=$(JMETER_DIRECTORY_OUTPUT)/output.xml
    python3 ../scripts/jtl_junit_converter.py $JMETER_RESULTS $JUNIT_RESULTS
  workingDirectory: ./terraform
  displayName: 'RESULTS: Convert JMeter Results to JUnit Format'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(JMETER_DIRECTORY_OUTPUT)/output.xml'
    failTaskOnFailedTests: false
  displayName: 'RESULTS: Publish Load Testing Results'

- publish: $(JMETER_DIRECTORY_OUTPUT)
  artifact: JMeterResults
  condition: succeededOrFailed()
  displayName: 'RESULTS: Publish Load Test Artifacts'

- script: terraform destroy -auto-approve
  workingDirectory: ./terraform
  displayName: 'TEARDOWN: Run Terraform Destroy'